### ISSUE TITLE
{filter: '*.txt'} returns empty files array

### ISSUE THREAD

**Issue by elmz87** [JS-DevTools/readdir-enhanced#14]
when i use filter: '*txt in my code it always return empty array
`readdir(path1, { basePath: path1, filter: "*.txt", deep: true}, function(err, files) {`

if i remove the filter i will show all the files in the directory including the subdirectories

**Comment by JamesMessinger** [comment]
`filter: "*.txt"` will only find text files in top-level directory.  If you want to find all text files at any level, then use a [globstar](https://www.npmjs.com/package/glob#glob-primer), like this: `filter: "**/*.txt"`
