### ISSUE TITLE
No files are streamed when you omit the 'data' handler.

### ISSUE THREAD

**Issue by emmerich** [JS-DevTools/readdir-enhanced#17]
I want to build a stream and only listen to files. I'm building it like so:

```javascript
const files = readdirEnhanced.readdirStreamStat('/tmp/test')

files.on('file', (file) => console.log(file))
files.on('end', () => console.log('end'))
```

If I run the above code, no files pass through the stream. If I add a data listener (even an empty function), things start moving:

```javascript
const files = readdirEnhanced.readdirStreamStat('/tmp/test')

files.on('data', () => {
  // no-op
})

files.on('file', (file) => console.log(file))
files.on('end', () => console.log('end'))
```

Is this intended behaviour? If so, I'm happy to update the documentation a bit to make it clearer why the data handler is needed.

Cheers

**Comment by JamesMessinger** [comment]
This behavior is part of the [Node.js Stream API](https://nodejs.org/api/stream.html#stream_stream).  It's important to understand [the two modes of a Readable stream](https://nodejs.org/api/stream.html#stream_two_reading_modes) and how to transition from "paused" mode to "flowing" mode.  Adding a "data" event handler is one of those ways.  You could also call `stream.resume()` or `stream.pipe()`.  A third (and more advanced) option is to call [`stream.read()`](https://nodejs.org/api/stream.html#stream_readable_read_size), but it has some caveats that are important to understand first.

As you suggested, it would be a good idea to add a little bit of "intro to streams" documentation, or at least some links to the relevant Node.js docs.  I'd be happy to merge a PR from you.

**Comment by JamesMessinger** [comment]
This is somewhat related to Issue #16 too, since it also has to do with documenting how to use the Stream API

**Comment by emmerich** [comment]
Got it. I thought I knew a decent amount about streaming in NodeJS but had never heard of paused vs. flowing modes so clearly the topic is more in depth that I believed!

I'll see if I can add some hints to the documentation without just copy/pasting the NodeJS documentation (maybe just dropping some links to relevant parts of the doc).
