### ISSUE TITLE
Why both `readdir-enhanced` and `@jsdevtools/readdir-enhanced` exist?

### ISSUE THREAD

**Issue by papb** [JS-DevTools/readdir-enhanced#22]
Why both [`readdir-enhanced`](https://www.npmjs.com/package/readdir-enhanced) and [`@jsdevtools/readdir-enhanced`](https://www.npmjs.com/package/@jsdevtools/readdir-enhanced) exist?

**Comment by JamesMessinger** [comment]
We recently moved all of our libraries to our NPM scope (`@jsdevtools`).  But we still publish to the old, non-scoped packages as well to provide backward compatibility.  Once most people have moved to the scoped packages, we'll deprecate the non-scoped ones.
